// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AdditionalCostController from "./additional_cost_controller"
application.register("additional-cost", AdditionalCostController)

import EditController from "./edit_controller"
application.register("edit", EditController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import QrCodeReaderController from "./qr_code_reader_controller"
application.register("qr-code-reader", QrCodeReaderController)
